name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 52.87.248.32 >> ~/.ssh/known_hosts

    # Step 3: Send shutdown signal to the remote application
    - name: Send shutdown signal
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@52.87.248.32 "echo 'shutdown' > /home/ubuntu/ACME-phase-2/ACME-Phase-2/shutdown_signal"

    # Step 4: Wait for the application to stop
    - name: Wait for application shutdown
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@52.87.248.32 "
          while [ -f /home/ubuntu/ACME-phase-2/ACME-Phase-2/running.lock ]; do
              echo 'Waiting for application to stop...';
              sleep 2;
          done
        "
        echo "Application stopped successfully."

    # Step 5: Upload the new code
    - name: Upload new code
      run: |
        scp -i ~/.ssh/id_rsa -r ./ACME-Phase-2 ubuntu@52.87.248.32:/home/ubuntu/ACME-phase-2/ACME-Phase-2

    # Step 6: Start the updated application
    - name: Start the new application
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@52.87.248.32 "
          cd /home/ubuntu/ACME-phase-2/ACME-Phase-2 &&
          nohup ./run_application.sh > application.log 2>&1 &
        "
      continue-on-error: false
