name: Continuous Deployment to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_RSA_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H 3.94.121.132 >> ~/.ssh/known_hosts
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.94.121.132 "cd /home/ubuntu/ACME-Phase-2 && bash -c './run install && cd user-interface && npx tsc app.ts --outDir dist --esModuleInterop && nohup node dist/app.js >> nohup.out 2>&1 &'"
      - name: Clean up SSH key
        run: |
          rm -f ~/.ssh/id_rsa
